### PR TITLE
🏗️ Migrate OpenAPI spec to YAML

### PR DESCRIPTION
**Pull request by RouisIbra**
Thank you for this great boilerplate.

I just migrated the OpenAPI spec file from JSON to YAML. YAML structure is cleaned for the eye and easier to read and write.

Everything updated in README as well.

### CODE REVIEW

**Comment by sidhantpanda** [comment]
Hey @RouisIbra, thank you for the PR!

There are 2 smalls things to take care of:
1. There were some changes to the yarn lock and which is now causing merge conflicts
2. Can you use the [js-yaml](https://www.npmjs.com/package/js-yaml) package instead to parse yaml to JSON?

**Comment by RouisIbra** [comment]
@sidhantpanda Done!

**Comment by sidhantpanda** [comment]
Looks good :)
Thanks a lot @RouisIbra !

**Comment by sidhantpanda** [comment]
FYI, I updated the logic to read the file only once and keep it in memory for all requests to the dev routes - 
https://github.com/sidhantpanda/docker-express-typescript-boilerplate/commit/e65a852da792eded1fd20448c6b84fa378344082

**Pull request merged**
